---
title: "final0"
execute:
    echo: false
    message: false
---

```{r}
library(tidytext)
library(dplyr)
library(stringr)
library(readr)
library(tidyr)
```

```{r}
dir1t <-  "/Users/user/Desktop/chosen arine/tom_sawyer.txt"
dir2t <- "/Users/user/Desktop/chosen arine/romeo_juliet.txt"
dir3t <- "/Users/user/Desktop/chosen arine/war_peace.txt"
```

```{r}
afinn <- get_sentiments("afinn")

positive <- get_sentiments("afinn") |> filter(value>0)

negative <- get_sentiments("afinn") |> filter(value<0)

lines1 <- read_lines(dir1t) 
dir1 <- tibble(text=lines1)
lines2 <- read_lines(dir2t) 
dir2 <- tibble(text=lines2)
lines3 <- read_lines(dir3t)
dir3 <- tibble(text=lines3)
```

```{r}
tidy_book1 <- dir1 %>% mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, regex("^chapter [ivxlc]+", ignore_case = TRUE)))) %>%
      unnest_tokens(word, text) %>% filter(chapter>0)
```

```{r}
sentiments1_pos <- tidy_book1 %>%
  inner_join(positive) %>%
  count(word, sort = TRUE)

sentiments1_neg <-tidy_book1 %>%
  inner_join(negative) %>%
  count(word, sort = TRUE)


word_scores <- tidy_book1 %>%
  count(word, sort = TRUE)
word_sentiments <- get_sentiments("afinn")
word_sentiment_data <- word_scores %>% left_join(word_sentiments, by = "word") |> mutate(word_avg_sent = n * value) %>% drop_na()
                                                     
word_sentiment_data

# count <- tidy_book1 %>% filter(word=="yes") %>% count(word) %>% pull(n)
# word_score <- get_sentiments("afinn") |> filter(word=="yes") |> pull(value)
# word_average_sentiment <- word_score * count

# print(word_average_sentiment)
```


```{r}
library(ggplot2)

word_sentiment_data |> ggplot(aes(word, word_avg_sent)) + geom_col() + scale_x_discrete(labels = NULL)
```



